### ISSUE TITLE
Instatag script tag contains redundant type attribute

### ISSUE THREAD

**Issue by danilo-factorial** [factorial-io/instatag#5]
Instatag script tag contains unnecessary/redundant type attribute which is not needed for JavaScript resources.

**Comment by danilo-factorial** [comment]
I created PR that addresses this issue.Can somebody please review it 
https://github.com/factorial-io/instatag/pull/6

**Comment by d34dman** [comment]
Thanks for the contribution, closing since, it has been merged.
